# Generated by Django 2.0.9 on 2018-12-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_selling',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products_selling',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
