# Generated by Django 2.0.9 on 2018-12-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20181209_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products_selling',
            options={},
        ),
        migrations.AlterField(
            model_name='products_selling',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterIndexTogether(
            name='products_selling',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='products_selling',
            name='slug',
        ),
    ]
