# Generated by Django 2.0.9 on 2018-12-09 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('seller', '0003_auto_20181210_0342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products_Leasing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname1', models.CharField(db_index=True, max_length=100)),
                ('description1', models.TextField()),
                ('stock', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=0)),
                ('image1', models.ImageField(upload_to='LeasingProductsPhotos')),
                ('leasing_period', models.IntegerField()),
                ('start_date', models.DateField(auto_now_add=True)),
                ('category1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_leasing', to='seller.Category')),
                ('leaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
        migrations.AlterField(
            model_name='products_selling',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_selling', to='seller.Category'),
        ),
    ]
