# Generated by Django 2.0.9 on 2018-12-11 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('seller', '0004_auto_20181210_0347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname2', models.CharField(max_length=100)),
                ('description2', models.TextField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile')),
            ],
        ),
    ]
