# Generated by Django 2.0.9 on 2018-12-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_commonnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_leasing',
            name='price1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
