# Generated by Django 2.0.9 on 2018-12-12 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_products_leasing_price1'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonnotification',
            name='request',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='seller.Request_table'),
        ),
    ]
