# Generated by Django 2.0.9 on 2018-12-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_notification_orders_leasing'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_buying',
            name='payment_type',
            field=models.CharField(choices=[('1', 'COD'), ('2', 'ONLINE')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='orders_leasing',
            name='payment_type',
            field=models.CharField(choices=[('1', 'COD'), ('2', 'ONLINE')], default='1', max_length=1),
        ),
    ]
