# Generated by Django 2.0.9 on 2018-12-12 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_commonnotification_request'),
        ('buyer', '0003_auto_20181212_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leasing_Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Products_Leasing')),
            ],
        ),
    ]
